name: heart_rate_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - matplotlib
  - tkinter
  - pip:
      - keyboard
      - pylsl
      - csv
      - bleak>=0.19.0
      - asyncio
